version: '3.8'

services:
  postgres:
    name: hacknarock_postgres
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nordic_peace_db
      POSTGRES_USER: nordic_peace
      POSTGRES_PASSWORD: nordic_peace
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared-network

  api:
    build: ./backend
    name: hacknarock_backend
    ports:
      - "8080:80"
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 80"
    volumes:
      - ./backend/app:/code/app
    depends_on:
      - postgres
    networks:
      - shared-network
  
  frontend:
    build: ./frontend
    name: hacknarock_frontend
    ports:
      - "8090:80"

volumes:
  postgres-data:

networks:
  shared-network:
